### ISSUE TITLE
getline 사용 후 *lineptr free

### ISSUE THREAD

**Issue by hui1601** [jisungbin/houses#1]
https://github.com/jisungbin/houses/blob/7abb1b44dc712e6744e74b98008094790c94da2c/c.c#L14
https://github.com/jisungbin/houses/blob/7abb1b44dc712e6744e74b98008094790c94da2c/c.c#L24
[getline man page](https://man7.org/linux/man-pages/man3/getline.3.html)를 보면 `getline(3)`에서 `char **restrict lineptr`이 `NULL`로 지정된 경우 메모리를 동적으로 할당합니다.
```
If *lineptr is set to NULL before the call, then getline() will allocate a buffer for storing the line.
```

사용자가 할당된 메모리를 항상 할당 해제해줘야한다 명시했습니다.
```
This buffer should be freed by the user program even if getline() failed.
```

다만, `*lineptr`이 할당된 상태에서는 `realloc(3)`를 수행하므로 마지막 사용 후 한번만 `free(1)`를 호출하시면 됩니다.
```
If the buffer is not large enough to hold the line, getline() resizes it with realloc(3), updating *lineptr and *n as necessary.
```

**Comment by jisungbin** [comment]
[https://github.com/jisungbin/houses/blob/main/c.c#L55](https://github.com/jisungbin/houses/blob/main/c.c#L55)
추가 하였는데 맞나요? C 언어를 배우지 않아 모르겠네요.

**Comment by hui1601** [comment]
`free(1)`에서 1은 linux man page의 목차번호입니다.
https://unix.stackexchange.com/a/3587
코드에서 `free(line)`으로 하시면 됩니다.

**Comment by hui1601** [comment]
https://github.com/jisungbin/houses/blob/58cb8785d3bab49f382880613ec358f8b08b00eb/c.c#L55
이 부분을 `free(line);`으로 바꾸시면 됩니다.

**Comment by jisungbin** [comment]
https://github.com/jisungbin/houses/blob/a2bd5db9307829fed7ed0953a0bb6d491df6615f/c.c#L55
감사합니다. 수정하였습니다.
